name: Deploy to AWS Lambda 

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t ./src
        working-directory: ${{ github.workspace }}

      - name: Create a ZIP package
        run: |
          cd src
          zip -r ../mypythonapp.zip .
        working-directory: ${{ github.workspace }}

      - name: Update AWS Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws lambda update-function-code \
            --function-name samplepython \
            --zip-file fileb://mypythonapp.zip \
            --region ap-south-1
        working-directory: ${{ github.workspace }}
